### ISSUE TITLE
Update to use grunt 1.0.0

### ISSUE THREAD

**Issue by pmchugh3** [danwellman/grunt-get-branchname#2]
Grunt has released 1.0.0, since this has a peer dependency on 0.4.5 then this cannot be used in conjunction with other up to date grunt plugins.

**Comment by danwellman** [comment]
Thanks, I've updated

**Comment by pmchugh3** [comment]
Thanks!

**Comment by pmchugh3** [comment]
Could you publish a new version with this please?

**Comment by danwellman** [comment]
Sure, I'll do this as soon as possible. I'm working at the moment, hope to get time this evening (I'm in UK, GMT+1 (BST) currently)

**Comment by danwellman** [comment]
Hey Peter, this is now done and updated in NPM and Github.
Thanks for the reminder!
